name = "Sharpneld"
author = "Haserius"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66c38f8c34fa04aaf78f7d040fc8a78354768ec1f995fd0a46654a9c26254f71"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = []
