name = "Sharpneld"
author = "Haserius"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2f3e00685da03a3c279e970f8ad86508622b740f8897ca44f662250b0adc61e"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = []
