name = "Sharpneld"
author = "Haserius"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a93b40dbf46fa5d60c45f1ffdd4ad2f2d46ebb585ec6b8f200d996f9a7353dd"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = []
