name = "Sharpneld"
author = "Haserius"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a24fe3cb62b93f2ee1bbc310caa6bc399c9f948b129400a463dfaac35e8d7f8"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = []
