name = "Sharpneld"
author = "Haserius"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ce029577e0185cbeb9248df28ccf1ca6c870e4c498ee434c7128305859065a2"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
unsup = "0.2.3"

[options]
acceptable-game-versions = []
