
#========================================================================
#
# All skills in pmmo are defined when they are used anywhere in PMMO.
# You do not need to define a skill here to use it. However, defining
# a skills attributes here will give you amore rounded skill list and
# a cleaner looking mod. Note that all the defaults here can be replaced
# if you wish. Also note that when using custom icon sizes they must be
# a square image(eg. 16x16, 24x24, 32x32) and they default to 18x18.
#
#========================================================================
[Skills]

	[Skills.Entry]

		[Skills.Entry.strength]
			maxLevel = 2147483647
			icon = "epicfight:textures/item/iron_longsword.png"
			iconSize = 8
			color = 10813440
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.vitality]
			maxLevel = 2147483647
			icon = "minecraft:textures/mob_effect/regeneration.png"
			iconSize = 8
			color = 10762049
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.endurance]
			maxLevel = 2147483647
			icon = "minecraft:textures/mob_effect/absorption.png"
			iconSize = 8
			color = 13762605
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.intelligence]
			maxLevel = 2147483647
			icon = "minecraft:textures/item/knowledge_book.png"
			iconSize = 8
			color = 2622620
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.dexterity]
			maxLevel = 2147483647
			icon = "epicfight:textures/item/iron_dagger.png"
			iconSize = 8
			color = 1809920
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.agility]
			maxLevel = 2147483647
			icon = "minecraft:textures/mob_effect/speed.png"
			iconSize = 8
			color = 6023229
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.gathering]
			maxLevel = 2147483647
			icon = "minecraft:textures/mob_effect/haste.png"
			iconSize = 8
			color = 16776448
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.building]
			maxLevel = 2147483647
			icon = "minecraft:textures/block/crafting_table_front.png"
			iconSize = 8
			color = 16773126
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.crafting]
			maxLevel = 2147483647
			icon = "minecraft:textures/block/crafting_table_top.png"
			iconSize = 8
			color = 16777014
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.charisma]
			maxLevel = 2147483647
			icon = "minecraft:textures/mob_effect/invisibility.png"
			iconSize = 8
			color = 4870138
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.perception]
			maxLevel = 2147483647
			icon = "minecraft:textures/item/ender_eye.png"
			iconSize = 8
			color = 2819218
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

		[Skills.Entry.knowledge]
			maxLevel = 5
			icon = "minecraft:textures/item/enchanted_book.png"
			iconSize = 8
			color = 11337724
			noAfkPenalty = false
			displayGroupName = false
			useTotalLevels = false

